### ISSUE TITLE
Odd issue with driver images fixed by reinstalling all docker images

### ISSUE THREAD

**Issue by juanjux** [bblfsh/sdk#238] opened 2018-03-01 12:13 UTC
Found while running the fixtures with a just build python-driver image and running the fixture regeneration: it didn't find the python 2 binary.

After deleting the docker image, I rebuild it and then when trying to install it into bblfshd it said:

 `"Installing python language driver from "bblfsh/python-driver:dev-21b075d-dirty"...
Error, manifest unknown: manifest unknown"`.

I deleted everything (`docker rmi (docker images -q) -f; and docker rm (docker ps -a -q) -f`), redownloaded bblfshd's image and then it worked. 

We should investigate this if it happens again.

**Comment by dennwc** [comment] 2018-08-02 14:54
Was not able to reproduce this. Closing for now.

**Closed by dennwc** 2018-08-02 14:54 UTC
Labels: bug
